Docs/readme
Vagabonds-Labs/cofiblocks pull request #73
Opened 2024-11-26 01:12 UTC by aguilar1x

## Description

Update Documentation in README.md and create other template for contributing guide

## Checklist

- [x] The title of the PR is clear and descriptive.
- [x] All tests have been run and passed.
- [x] Code follows project conventions (Biome formatting, linting).
- [x] Documentation has been updated as needed.
- [x] Commit messages follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) style.

## Type of Change

- [ ] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Chore
- [x] Documentation
- [ ] Test

## Testing

### Manual Testing
N/A

### Automated Tests
N/A

## Additional Notes

Update Documentation in README.md and create other template for contributing guide

2024-11-27 00:57 UTC, rvalenciano commented
@aguilar1x this looks great! Can you please add the link to the issue we are solving?

2024-11-27 02:09 UTC, evgongora reviewed
Awesome job, just a few changes! :)

2024-11-27 02:09 UTC, evgongora commented on README.md
> +At the end of the first year, all CofiBlocks members will receive a percentage of the pilot's financial results in cryptocurrency based on their accumulated COFI tokens. Members will also have the op
This is already in the faq section but you can still reference it

2024-11-27 02:09 UTC, evgongora commented on README.md
> +### 💻 **DEVS**
can you change this to maintainers?

2024-11-29 02:27 UTC, evgongora reviewed
So far we have just one change, and also Randy will contact you for the docker setup process. Thank you so much! This is almost ready :)

2024-11-29 02:27 UTC, evgongora commented on README.md
> +- revert: Reverts a previous commit.
Since there is already a link to conventional commits can you just do a few examples of types?

2024-11-30 13:09 UTC, evgongora requested changes

2024-11-30 13:09 UTC, evgongora commented on CONTRIBUTING.md
Please remove contribution.md since is not part of the issue.

2024-12-01 04:50 UTC, evgongora approved these changes

2024-12-01 04:50 UTC, evgongora commented
Thank you so much! Great effort :)

2024-12-01 04:51 UTC, merged